version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: flashcard-mysql
    restart: always
    environment:
      MYSQL_DATABASE: flashcard
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: 