version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: flashcard-postgres
    restart: always
    environment:
      POSTGRES_DB: flashcard
      POSTGRES_USER: flashcard_user
      POSTGRES_PASSWORD: flashcard_pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - flashcard-network

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: flashcard-backend
    restart: always
    environment:
      DATABASE_HOST: db
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - flashcard-network

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    container_name: flashcard-frontend
    restart: always
    environment:
      VITE_API_BASE_URL: http://localhost:8080/api/v1
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - flashcard-network

volumes:
  db_data:

networks:
  flashcard-network:
    driver: bridge 