# Spring Boot Application Configuration

# Database Configuration
spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:5432/flashcard
    username: flashcard_user
    password: flashcard_pass
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  # Flyway Configuration (disabled)
  flyway:
    enabled: false

  # Thymeleaf Configuration
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

# Logging Configuration
logging:
  file:
    name: logs/flashcard-app.log
  level:
    root: INFO

# JWT Configuration
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method