# Docker-specific configuration

# Database Configuration for Docker
spring:
  datasource:
    url: jdbc:postgresql://db:5432/flashcard
    username: flashcard_user
    password: flashcard_pass
    driver-class-name: org.postgresql.Driver

  # JPA Configuration for Docker
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
    show-sql: false

  # Disable Flyway for now
  flyway:
    enabled: false

  # Thymeleaf Configuration
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

# Logging Configuration for Docker
logging:
  level:
    root: INFO
    com.app.flashcard: DEBUG

# JWT Configuration
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method